### ISSUE TITLE
cv2 installation issue

### ISSUE THREAD

**Issue by rbnpi** [justinplatz/SecurityCam#2]
In your article http://www.pubnub.com/blog/create-realtime-raspberry-pi-security-camera-w-parse/ you give the reference http://www.pyimagesearch.com/2015/02/23/install-opencv-and-python-on-your-raspberry-pi-2-and-b/ for installing cv2. I have done this successfully, but it installs in a virtual environment cv2 which has to be active to use it. I'm not sure how to reconcile this with the other bits of code in your project which do not want this.

**Comment by GleasonK** [comment]
Hello,
First, thank you for raising this issue!
You should not use it in the virtual environment, I will update that portion and explicitly state that shortly. Are you running into any errors trying to use cv2 outside of the virtual environment? 

To paraphrase a piece of the guide:

# Step 10:

If you’ve gotten this far...OpenCV should now be installed in:
    `/usr/local/lib/python2.7/site-packages`

...in order to use in virtual environment...

```
$ cd ~/.virtualenvs/cv/lib/python2.7/site-packages/
$ ln -s /usr/local/lib/python2.7/site-packages/cv2.so cv2.so
$ ln -s /usr/local/lib/python2.7/site-packages/cv.py cv.py
```

This was done so that the virtualenv could use cv2, it should already be accessible to the normal environment. If you have an issue importing cv2 outside of the virtualenv let me know.

**Comment by rbnpi** [comment]
Dear Kevin

I am still having problems with this. The cv2 install ONLY appears to work from the virtual environment. It is compiled there (as per the instructions in the article you suggest using at http://www.pyimagesearch.com/2015/02/23/install-opencv-and-python-on-your-raspberry-pi-2-and-b/) If I use import cv2 from the normal environment it is not found.
Is there anyway it can be linked in so that it will wrk? 

I don’t really wan’t to recompile it as it takes several hours to do!
alternatively is there another install you can suggest fro opencv on the Raspberry Pi that will work in the normal user environment.

Robin

**Comment by GleasonK** [comment]
First let me say I'm sorry this is happening, perhaps we preconfigured our pi for another project and didn't realize that it effected us this time around, but assuming your cv2 installation succeeded, it seems like python simply cannot locate the files. I'm going to just ramble off a few ideas and things for you to try:

First confirm that cv2 is downloaded where we think it is, on you pi terminal

```
$ cd /usr/local/lib/python2.7/site-packages/
$ ls
```

And make sure you see cv2.py and cv2.so. If not, that is where the issue might be.

If you see them there, then it appears that your python is not looking in `/usr/local/lib/python2.7/site-packages/` folder. Are you using Python 2.7? 

```
$ python --version
```

This will tell your your python version. If it isn't 2.7.x then your python framework would not look in /usr/local/lib/**python2.7**/site-packages/. 

If this is the case you could try moving the files, but I'm not sure of the compatibility of this.

**If you see the cv2 files in site-packages, no need to recompile. We just need to point python to where they are.**

Python looks in the following directories

```
>>> import sys
>>> print sys.path
```

Take a look at what that prints out. As a one time test, you can try to modify this path (don't worry, it will revert back to its original value when you quit the shell).

```
>>> sys.path.append("/usr/local/lib/python2.7/site-packages/")
>>> import cv2
```

Tell me if any of that works for you and we can continue discussing a solution.

**Comment by rbnpi** [comment]
HI Kevin
I tried everything below and it then links cv2 ok. Not tried if it works properly yet though. What do you suggest next?
Robin

**Comment by rbnpi** [comment]
Dear Kevin

My original path for python2.7 did not include the site-packages directory, so I have put a path file my-oepncv2.pth inside the dist-packages directory which is in the path, and now it sees it.
I tested cv2 and it is working ok, although it was built against a later version of numpy 1.9.2 rather than numpy 1,6,2 which is in the main environment .
I have now got an alternative project http://www.pyimagesearch.com/2015/06/01/home-surveillance-and-motion-detection-with-the-raspberry-pi-python-and-opencv/
This is from the same guy who wrote the opencv install article.
working in both the virtual and main environments.

I have encountered one other problem. pip does not seem to work in the normal environment but gives permission errors, unlike in the virtual one where it is ok.
I have had to resort to using sudo pip install in the main environment which is a bit dodgy, but has installed all the packages required.

I am now pressing on with the pubnub project. I have parse installed and working and pubnub keys set up so hopefully am on the final stage.
Hope to finish it later on today.

Robin

**Comment by GleasonK** [comment]
Good, Glad to hear it! Let me know if you have any other troubles!

**Comment by rbnpi** [comment]
One question. Does the project work with the basic free pubnub  account or does it need a paid one?

**Comment by justinplatz** [comment]
Your free account is all you need to get started!
